[book]
authors = ["shilangyu"]
language = "en"
multilingual = false
src = "src"
title = "Uni notes"

[output.html.fold]
enable = true
level = 1

[preprocessor.katex]
command = "python katex.py"
renderer = ["html"]
